import React from "react";
import ReportProblemIcon from "@mui/icons-material/ReportProblem";
import InfoIcon from "@mui/icons-material/Info";
import AutorenewIcon from "@mui/icons-material/Autorenew";
import DoneIcon from "@mui/icons-material/Done";
import Chip from "@mui/material/Chip";
import { styled } from "@mui/material/styles";

const StyledChip = styled(Chip)(({ theme }) => ({
    justifyContent: "left",
    "& .icon": {
        color: "inherit"
    },
    "&.inactive": {
        color: theme.palette.info.dark,
        border: `1px solid ${theme.palette.info.main}`
    },
    "&.active": {
        color: theme.palette.success.dark,
        border: `1px solid ${theme.palette.success.main}`
    },
    "&.PartiallyFilled": {
        color: theme.palette.warning.dark,
        border: `1px solid ${theme.palette.warning.main}`
    },
    "&.banned": {
        color: theme.palette.error.dark,
        border: `1px solid ${theme.palette.error.main}`
    }
}));

const Status = (props) => {
    const { status } = props;

    let icon = null;
    if (status === "active") {
        icon = <DoneIcon className="icon" />;
    } else if (status === "inactive") {
        icon = <InfoIcon className="icon" />;
    }

    let label = status;
    if (status === "PartiallyFilled") {
        label = "Partially Filled";
    }

    return (
        <StyledChip
            className={status}
            icon={icon}
            size="small"
            label={label}
            variant="outlined"
        />
    );
};

export default function renderStatus(params) {
    console.log("renderStatus(params)", params);
    if (params.rowNode.isAutoGenerated || params.value == null) {
        return "";
    }

    return <Status status={params.value} />;
}
