import React from "react";
import ReportProblemIcon from "@mui/icons-material/ReportProblem";
import InfoIcon from "@mui/icons-material/Info";
import AutorenewIcon from "@mui/icons-material/Autorenew";
import DoneIcon from "@mui/icons-material/Done";
import Chip from "@mui/material/Chip";
import { styled } from "@mui/material/styles";

const StyledChip = styled(Chip)(({ theme }) => ({
    justifyContent: "left",
    "& .icon": {
        color: "inherit"
    },
    "&.Inactive": {
        color: theme.palette.info.dark,
        border: `1px solid ${theme.palette.info.main}`
    },
    "&.Active": {
        color: theme.palette.success.dark,
        border: `1px solid ${theme.palette.success.main}`
    },
    "&.banned": {
        color: theme.palette.error.dark,
        border: `1px solid ${theme.palette.error.main}`
    }
}));

const Status = (props) => {
    const { status } = props;

    let className = null;
    let label = status;
    let icon = null;
    if (status == 1) {
        icon = <DoneIcon className="icon" />;
        label = 'Active';
        className = label;
    } else if (status === 0) {
        label = 'Inactive';
        className = label;
        icon = <InfoIcon className="icon" />;
    }

    return (
        <StyledChip
            className={className}
            icon={icon}
            size="small"
            label={label}
            variant="outlined"
        />
    );
};

export default function renderStatus(params) {
    if (params.rowNode.isAutoGenerated || params.value == null) {
        return "";
    }

    return <Status status={params.value} />;
}
